Repository Minestom/Minestom, pull requests merged in 2025-01, with the labels that each got.

#2607 Update ClientVehicleMovePacket to 1.21.4
  src/main/java/net/minestom/server/network/packet/client/play/ClientVehicleMovePacket.java
  src/test/java/net/minestom/server/network/PacketWriteReadTest.java
Labels: enhancement

#2621 refactor: move from getUniqueId() to getUuid() and related
  src/main/java/net/minestom/server/instance/Instance.java
  src/main/java/net/minestom/server/instance/InstanceContainer.java
  src/main/java/net/minestom/server/instance/InstanceManager.java
  src/main/java/net/minestom/server/instance/SharedInstance.java
  src/main/java/net/minestom/server/instance/batch/ChunkBatch.java
  src/main/java/net/minestom/server/listener/SpectateListener.java
  src/main/java/net/minestom/server/scoreboard/TeamManager.java
  src/main/java/net/minestom/server/tag/Serializers.java
  src/main/java/net/minestom/server/utils/UUIDUtils.java
  src/main/java/net/minestom/server/utils/nbt/BinaryTagSerializer.java
  src/test/java/net/minestom/server/instance/InstanceUnregisterIntegrationTest.java
Labels: api breaking

#2622 chore: Add pull request template
  .github/pull_request_template.md
Labels: documentation, enhancement

#2624 chore: Add issue templates for more structure
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/performance.yml
Labels: documentation, enhancement

#2628 chore: Rework workflows for github
  .github/old-workflows/check-pr-style.yml
  .github/old-workflows/codeql-analysis.yml
  .github/workflows/build-pr.yml
  .github/workflows/build.yml
  .github/workflows/close_invalid_prs.yml
  .github/workflows/javadoc.yml
  .github/workflows/pr.yml
  .github/workflows/snapshot-deploy.yaml
  .github/workflows/trigger-jitpack-build.yml
Labels: Publish Pull Request

#2632 Add missing `@n` selector to ArgumentEntity
  src/main/java/net/minestom/server/command/builder/arguments/minecraft/ArgumentEntity.java
  src/main/java/net/minestom/server/utils/entity/EntityFinder.java
Labels: bug
